import enum


class AuthorType(enum.Enum):
    """How a message was produced on the reader side.

    - HUMAN_PSYCHIC: typed by a human (the reader, or an admin connected as the
      reader). This is also the backfill value for every pre-existing message.
    - AI_DRAFTED: generated by the AI pipeline (Valentina) and delivered as the
      reader — either auto-sent after Sabri passed it, or sent by an admin from
      the draft-review box.
    - ADMIN: reserved for a message an admin sends acting explicitly as an admin
      (not as the reader). Currently unused by the auto flow.
    - SYSTEM: platform system message (no human/AI author).
    """

    HUMAN_PSYCHIC = "HUMAN_PSYCHIC"
    AI_DRAFTED = "AI_DRAFTED"
    ADMIN = "ADMIN"
    SYSTEM = "SYSTEM"
