import enum


class NoteSource(enum.Enum):
    """Where a client-dossier note came from.

    - HUMAN: written by a psychic/admin (the original dossier behaviour). This is
      the backfill value for every pre-existing note.
    - AI_ATLAS: auto-generated by Atlas at session end. Clearly tagged so it is
      visually distinct from — and never overwrites — human-written notes.
    """

    HUMAN = "HUMAN"
    AI_ATLAS = "AI_ATLAS"
