from enum import Enum


class NotificationType(str, Enum):
    CHAT_ACCEPTED = "CHAT_ACCEPTED"
    CHAT_ENDED = "CHAT_ENDED"
    CHAT_REQUESTED = "CHAT_REQUESTED"
    CHAT_REQUEST_CANCELLED = "CHAT_REQUEST_CANCELLED"
    CHAT_PAUSED = "CHAT_PAUSED"
    CHAT_PAUSED_INSUFFICIENT_FUNDS = "CHAT_PAUSED_INSUFFICIENT_FUNDS"
    CHAT_RESUMED = "CHAT_RESUMED"
    MESSAGE_RECEIVED = "MESSAGE_RECEIVED"
    BALANCE_LOW = "BALANCE_LOW"
    SESSION_ENDING_SOON = "SESSION_ENDING_SOON"
    SESSION_ENDED_NO_BALANCE = "SESSION_ENDED_NO_BALANCE"
