from enum import Enum


class NotificationType(str, Enum):
    CHAT_ACCEPTED = "CHAT_ACCEPTED"
    CHAT_ENDED = "CHAT_ENDED"
    CHAT_REQUESTED = "CHAT_REQUESTED"
    CHAT_REQUEST_CANCELLED = "CHAT_REQUEST_CANCELLED"
    CHAT_PAUSED = "CHAT_PAUSED"
    CHAT_PAUSED_INSUFFICIENT_FUNDS = "CHAT_PAUSED_INSUFFICIENT_FUNDS"
    CHAT_RESUMED = "CHAT_RESUMED"
    BALANCE_LOW = "BALANCE_LOW"
    INSUFFICIENT_BALANCE_AFTER_PAYMENT = "INSUFFICIENT_BALANCE_AFTER_PAYMENT"
    PAYMENT_SUCCESS_CHAT_NEEDS_MANUAL_RESUME = (
        "PAYMENT_SUCCESS_CHAT_NEEDS_MANUAL_RESUME"
    )
    RESUME_ERROR_AFTER_PAYMENT = "RESUME_ERROR_AFTER_PAYMENT"
    TOPUP_SUCCESS = "TOPUP_SUCCESS"
