/* Every country a reader's ethnicity may name (ROUND56): each officially
   assigned ISO 3166-1 alpha-2 code with the country's name and its demonym,
   all 249. The server keeps the same codes (TAROT-BACKEND
   app/enums/country_codes.py ISO_COUNTRY_CODES) and refuses any other;
   scripts/test-countries.mts proves the two lists hold exactly the same codes.
   A reader's ethnicity is stored as one or two codes, comma separated ("MA",
   "GB,RO"). Places with no people of their own carry the demonym of the
   country they belong to. */

export interface Country {
  code: string;
  name: string;
  demonym: string;
}

const COUNTRY_ROWS: readonly (readonly [code: string, name: string, demonym: string])[] = [
  ["AD", "Andorra", "Andorran"],
  ["AE", "United Arab Emirates", "Emirati"],
  ["AF", "Afghanistan", "Afghan"],
  ["AG", "Antigua and Barbuda", "Antiguan"],
  ["AI", "Anguilla", "Anguillian"],
  ["AL", "Albania", "Albanian"],
  ["AM", "Armenia", "Armenian"],
  ["AO", "Angola", "Angolan"],
  ["AQ", "Antarctica", "Antarctic"],
  ["AR", "Argentina", "Argentinian"],
  ["AS", "American Samoa", "American Samoan"],
  ["AT", "Austria", "Austrian"],
  ["AU", "Australia", "Australian"],
  ["AW", "Aruba", "Aruban"],
  ["AX", "Åland Islands", "Ålander"],
  ["AZ", "Azerbaijan", "Azerbaijani"],
  ["BA", "Bosnia and Herzegovina", "Bosnian"],
  ["BB", "Barbados", "Barbadian"],
  ["BD", "Bangladesh", "Bangladeshi"],
  ["BE", "Belgium", "Belgian"],
  ["BF", "Burkina Faso", "Burkinabè"],
  ["BG", "Bulgaria", "Bulgarian"],
  ["BH", "Bahrain", "Bahraini"],
  ["BI", "Burundi", "Burundian"],
  ["BJ", "Benin", "Beninese"],
  ["BL", "Saint Barthélemy", "Barthélemois"],
  ["BM", "Bermuda", "Bermudian"],
  ["BN", "Brunei", "Bruneian"],
  ["BO", "Bolivia", "Bolivian"],
  ["BQ", "Caribbean Netherlands", "Caribbean Dutch"],
  ["BR", "Brazil", "Brazilian"],
  ["BS", "Bahamas", "Bahamian"],
  ["BT", "Bhutan", "Bhutanese"],
  ["BV", "Bouvet Island", "Norwegian"],
  ["BW", "Botswana", "Botswanan"],
  ["BY", "Belarus", "Belarusian"],
  ["BZ", "Belize", "Belizean"],
  ["CA", "Canada", "Canadian"],
  ["CC", "Cocos (Keeling) Islands", "Cocos Islander"],
  ["CD", "DR Congo", "Congolese"],
  ["CF", "Central African Republic", "Central African"],
  ["CG", "Congo", "Congolese"],
  ["CH", "Switzerland", "Swiss"],
  ["CI", "Côte d’Ivoire", "Ivorian"],
  ["CK", "Cook Islands", "Cook Islander"],
  ["CL", "Chile", "Chilean"],
  ["CM", "Cameroon", "Cameroonian"],
  ["CN", "China", "Chinese"],
  ["CO", "Colombia", "Colombian"],
  ["CR", "Costa Rica", "Costa Rican"],
  ["CU", "Cuba", "Cuban"],
  ["CV", "Cape Verde", "Cape Verdean"],
  ["CW", "Curaçao", "Curaçaoan"],
  ["CX", "Christmas Island", "Christmas Islander"],
  ["CY", "Cyprus", "Cypriot"],
  ["CZ", "Czechia", "Czech"],
  ["DE", "Germany", "German"],
  ["DJ", "Djibouti", "Djiboutian"],
  ["DK", "Denmark", "Danish"],
  ["DM", "Dominica", "Dominican"],
  ["DO", "Dominican Republic", "Dominican"],
  ["DZ", "Algeria", "Algerian"],
  ["EC", "Ecuador", "Ecuadorian"],
  ["EE", "Estonia", "Estonian"],
  ["EG", "Egypt", "Egyptian"],
  ["EH", "Western Sahara", "Sahrawi"],
  ["ER", "Eritrea", "Eritrean"],
  ["ES", "Spain", "Spanish"],
  ["ET", "Ethiopia", "Ethiopian"],
  ["FI", "Finland", "Finnish"],
  ["FJ", "Fiji", "Fijian"],
  ["FK", "Falkland Islands", "Falkland Islander"],
  ["FM", "Micronesia", "Micronesian"],
  ["FO", "Faroe Islands", "Faroese"],
  ["FR", "France", "French"],
  ["GA", "Gabon", "Gabonese"],
  ["GB", "United Kingdom", "British"],
  ["GD", "Grenada", "Grenadian"],
  ["GE", "Georgia", "Georgian"],
  ["GF", "French Guiana", "French Guianese"],
  ["GG", "Guernsey", "Guernsey"],
  ["GH", "Ghana", "Ghanaian"],
  ["GI", "Gibraltar", "Gibraltarian"],
  ["GL", "Greenland", "Greenlandic"],
  ["GM", "Gambia", "Gambian"],
  ["GN", "Guinea", "Guinean"],
  ["GP", "Guadeloupe", "Guadeloupean"],
  ["GQ", "Equatorial Guinea", "Equatorial Guinean"],
  ["GR", "Greece", "Greek"],
  ["GS", "South Georgia and the South Sandwich Islands", "British"],
  ["GT", "Guatemala", "Guatemalan"],
  ["GU", "Guam", "Guamanian"],
  ["GW", "Guinea-Bissau", "Bissau-Guinean"],
  ["GY", "Guyana", "Guyanese"],
  ["HK", "Hong Kong", "Hongkonger"],
  ["HM", "Heard Island and McDonald Islands", "Australian"],
  ["HN", "Honduras", "Honduran"],
  ["HR", "Croatia", "Croatian"],
  ["HT", "Haiti", "Haitian"],
  ["HU", "Hungary", "Hungarian"],
  ["ID", "Indonesia", "Indonesian"],
  ["IE", "Ireland", "Irish"],
  ["IL", "Israel", "Israeli"],
  ["IM", "Isle of Man", "Manx"],
  ["IN", "India", "Indian"],
  ["IO", "British Indian Ocean Territory", "Chagossian"],
  ["IQ", "Iraq", "Iraqi"],
  ["IR", "Iran", "Iranian"],
  ["IS", "Iceland", "Icelandic"],
  ["IT", "Italy", "Italian"],
  ["JE", "Jersey", "Jersey"],
  ["JM", "Jamaica", "Jamaican"],
  ["JO", "Jordan", "Jordanian"],
  ["JP", "Japan", "Japanese"],
  ["KE", "Kenya", "Kenyan"],
  ["KG", "Kyrgyzstan", "Kyrgyz"],
  ["KH", "Cambodia", "Cambodian"],
  ["KI", "Kiribati", "I-Kiribati"],
  ["KM", "Comoros", "Comorian"],
  ["KN", "Saint Kitts and Nevis", "Kittitian"],
  ["KP", "North Korea", "North Korean"],
  ["KR", "South Korea", "South Korean"],
  ["KW", "Kuwait", "Kuwaiti"],
  ["KY", "Cayman Islands", "Caymanian"],
  ["KZ", "Kazakhstan", "Kazakh"],
  ["LA", "Laos", "Lao"],
  ["LB", "Lebanon", "Lebanese"],
  ["LC", "Saint Lucia", "Saint Lucian"],
  ["LI", "Liechtenstein", "Liechtensteiner"],
  ["LK", "Sri Lanka", "Sri Lankan"],
  ["LR", "Liberia", "Liberian"],
  ["LS", "Lesotho", "Basotho"],
  ["LT", "Lithuania", "Lithuanian"],
  ["LU", "Luxembourg", "Luxembourgish"],
  ["LV", "Latvia", "Latvian"],
  ["LY", "Libya", "Libyan"],
  ["MA", "Morocco", "Moroccan"],
  ["MC", "Monaco", "Monégasque"],
  ["MD", "Moldova", "Moldovan"],
  ["ME", "Montenegro", "Montenegrin"],
  ["MF", "Saint Martin", "Saint-Martinois"],
  ["MG", "Madagascar", "Malagasy"],
  ["MH", "Marshall Islands", "Marshallese"],
  ["MK", "North Macedonia", "Macedonian"],
  ["ML", "Mali", "Malian"],
  ["MM", "Myanmar", "Burmese"],
  ["MN", "Mongolia", "Mongolian"],
  ["MO", "Macao", "Macanese"],
  ["MP", "Northern Mariana Islands", "Northern Mariana Islander"],
  ["MQ", "Martinique", "Martinican"],
  ["MR", "Mauritania", "Mauritanian"],
  ["MS", "Montserrat", "Montserratian"],
  ["MT", "Malta", "Maltese"],
  ["MU", "Mauritius", "Mauritian"],
  ["MV", "Maldives", "Maldivian"],
  ["MW", "Malawi", "Malawian"],
  ["MX", "Mexico", "Mexican"],
  ["MY", "Malaysia", "Malaysian"],
  ["MZ", "Mozambique", "Mozambican"],
  ["NA", "Namibia", "Namibian"],
  ["NC", "New Caledonia", "New Caledonian"],
  ["NE", "Niger", "Nigerien"],
  ["NF", "Norfolk Island", "Norfolk Islander"],
  ["NG", "Nigeria", "Nigerian"],
  ["NI", "Nicaragua", "Nicaraguan"],
  ["NL", "Netherlands", "Dutch"],
  ["NO", "Norway", "Norwegian"],
  ["NP", "Nepal", "Nepali"],
  ["NR", "Nauru", "Nauruan"],
  ["NU", "Niue", "Niuean"],
  ["NZ", "New Zealand", "New Zealander"],
  ["OM", "Oman", "Omani"],
  ["PA", "Panama", "Panamanian"],
  ["PE", "Peru", "Peruvian"],
  ["PF", "French Polynesia", "French Polynesian"],
  ["PG", "Papua New Guinea", "Papua New Guinean"],
  ["PH", "Philippines", "Filipino"],
  ["PK", "Pakistan", "Pakistani"],
  ["PL", "Poland", "Polish"],
  ["PM", "Saint Pierre and Miquelon", "Saint-Pierrais"],
  ["PN", "Pitcairn Islands", "Pitcairn Islander"],
  ["PR", "Puerto Rico", "Puerto Rican"],
  ["PS", "Palestine", "Palestinian"],
  ["PT", "Portugal", "Portuguese"],
  ["PW", "Palau", "Palauan"],
  ["PY", "Paraguay", "Paraguayan"],
  ["QA", "Qatar", "Qatari"],
  ["RE", "Réunion", "Réunionese"],
  ["RO", "Romania", "Romanian"],
  ["RS", "Serbia", "Serbian"],
  ["RU", "Russia", "Russian"],
  ["RW", "Rwanda", "Rwandan"],
  ["SA", "Saudi Arabia", "Saudi"],
  ["SB", "Solomon Islands", "Solomon Islander"],
  ["SC", "Seychelles", "Seychellois"],
  ["SD", "Sudan", "Sudanese"],
  ["SE", "Sweden", "Swedish"],
  ["SG", "Singapore", "Singaporean"],
  ["SH", "Saint Helena, Ascension and Tristan da Cunha", "Saint Helenian"],
  ["SI", "Slovenia", "Slovenian"],
  ["SJ", "Svalbard and Jan Mayen", "Norwegian"],
  ["SK", "Slovakia", "Slovak"],
  ["SL", "Sierra Leone", "Sierra Leonean"],
  ["SM", "San Marino", "Sammarinese"],
  ["SN", "Senegal", "Senegalese"],
  ["SO", "Somalia", "Somali"],
  ["SR", "Suriname", "Surinamese"],
  ["SS", "South Sudan", "South Sudanese"],
  ["ST", "São Tomé and Príncipe", "São Toméan"],
  ["SV", "El Salvador", "Salvadoran"],
  ["SX", "Sint Maarten", "Sint Maartener"],
  ["SY", "Syria", "Syrian"],
  ["SZ", "Eswatini", "Swazi"],
  ["TC", "Turks and Caicos Islands", "Turks and Caicos Islander"],
  ["TD", "Chad", "Chadian"],
  ["TF", "French Southern Territories", "French"],
  ["TG", "Togo", "Togolese"],
  ["TH", "Thailand", "Thai"],
  ["TJ", "Tajikistan", "Tajik"],
  ["TK", "Tokelau", "Tokelauan"],
  ["TL", "Timor-Leste", "Timorese"],
  ["TM", "Turkmenistan", "Turkmen"],
  ["TN", "Tunisia", "Tunisian"],
  ["TO", "Tonga", "Tongan"],
  ["TR", "Turkey", "Turkish"],
  ["TT", "Trinidad and Tobago", "Trinidadian"],
  ["TV", "Tuvalu", "Tuvaluan"],
  ["TW", "Taiwan", "Taiwanese"],
  ["TZ", "Tanzania", "Tanzanian"],
  ["UA", "Ukraine", "Ukrainian"],
  ["UG", "Uganda", "Ugandan"],
  ["UM", "United States Minor Outlying Islands", "American"],
  ["US", "United States", "American"],
  ["UY", "Uruguay", "Uruguayan"],
  ["UZ", "Uzbekistan", "Uzbek"],
  ["VA", "Vatican City", "Vatican"],
  ["VC", "Saint Vincent and the Grenadines", "Vincentian"],
  ["VE", "Venezuela", "Venezuelan"],
  ["VG", "British Virgin Islands", "British Virgin Islander"],
  ["VI", "US Virgin Islands", "US Virgin Islander"],
  ["VN", "Vietnam", "Vietnamese"],
  ["VU", "Vanuatu", "Ni-Vanuatu"],
  ["WF", "Wallis and Futuna", "Wallisian"],
  ["WS", "Samoa", "Samoan"],
  ["YE", "Yemen", "Yemeni"],
  ["YT", "Mayotte", "Mahoran"],
  ["ZA", "South Africa", "South African"],
  ["ZM", "Zambia", "Zambian"],
  ["ZW", "Zimbabwe", "Zimbabwean"],
];

export const COUNTRIES: readonly Country[] = COUNTRY_ROWS.map(([code, name, demonym]) => ({ code, name, demonym }));

const BY_CODE = new Map(COUNTRIES.map((country) => [country.code, country]));

/* How the server joins her codes (TAROT-BACKEND app/enums/country_codes.py
   ETHNICITY_SEPARATOR). */
export const ETHNICITY_SEPARATOR = ",";

/* Her countries, in the order stored, when every part of a stored ethnicity is
   a code on the list; null for an empty value or for free text kept from
   before ROUND56. */
export function countriesOf(ethnicity: string | null | undefined): Country[] | null {
  if (!ethnicity) return null;
  const countries = ethnicity.split(ETHNICITY_SEPARATOR).map((code) => BY_CODE.get(code));
  return countries.every((country): country is Country => country !== undefined) ? countries : null;
}

/* The flag emoji of a code: its two letters as regional indicator symbols. */
const REGIONAL_INDICATOR_A = 0x1f1e6;
export const flagOf = (code: string) =>
  String.fromCodePoint(...[...code].map((letter) => REGIONAL_INDICATOR_A + letter.charCodeAt(0) - "A".charCodeAt(0)));

/* As clients read it: "🇲🇦 Moroccan", or "🇬🇧 🇷🇴 British · Romanian". */
export function ethnicityLine(ethnicity: string | null | undefined): string | null {
  const countries = countriesOf(ethnicity);
  if (!countries) return null;
  return `${countries.map((country) => flagOf(country.code)).join(" ")} ${countries.map((country) => country.demonym).join(" · ")}`;
}
