FROM node:22-alpine AS build

ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

WORKDIR /app

# 1. Copy package.json and package-lock.json (Drop yarn.lock since it's deleted)
COPY package.json package-lock.json ./

# 2. Use clean npm install
RUN npm ci

COPY . .

# 3. Build using npm
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]